=== UO266499/sew-mayo/XML/Ejercicio-1/Tarea-2/rutas.dtd
<!ELEMENT rutasCaballo (ruta+)>
<!ELEMENT ruta (tipo, dificultad, duracion, inicio?, hora?, agencia, descripcion, personas, lugar, direccion, coordenadas, bibliografias, recomendacion, hitos)>
<!ELEMENT hitos (hito+)>
<!ELEMENT hito (nombre, descripcion, coordenadas, distancia, tiempo?,fotos+, videos?)>
<!ELEMENT bibliografias (bibliografia+)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT dificultad (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT inicio (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT agencia (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT personas (#PCDATA)>
<!ELEMENT lugar (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT coordenadas (#PCDATA)>
<!ELEMENT bibliografia (#PCDATA)>
<!ELEMENT recomendacion (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT distancia (#PCDATA)>
<!ELEMENT fotos (foto+)>
<!ELEMENT foto (#PCDATA)>
<!ELEMENT tiempo (#PCDATA)>
<!ELEMENT videos (video*)>
<!ELEMENT video (#PCDATA)>
<!ATTLIST ruta
	titulo CDATA #REQUIRED>
<!ATTLIST coordenadas
	longitud CDATA #REQUIRED>
<!ATTLIST coordenadas
	latitud  CDATA #REQUIRED>
<!ATTLIST coordenadas
	altitud CDATA #REQUIRED>
<!ATTLIST distancia
	km CDATA #REQUIRED>
<!ATTLIST foto
	link CDATA #REQUIRED>
<!ATTLIST bibliografia
	link CDATA #REQUIRED>
<!ATTLIST video
	link CDATA #IMPLIED>

=== UO266499/sew-mayo/XML/Ejercicio-2/Tarea-1/rutasCaballo.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<!DOCTYPE rutasCaballo SYSTEM "rutas.dtd">
<rutasCaballo>
  <ruta titulo = "Caballos en Cangas de Onís">
        <tipo>Turistica</tipo>
		<dificultad>7</dificultad>
        <duracion>2 horas</duracion>
        <inicio>15/05/2021</inicio>
        <hora>09:00</hora>
		<agencia>Aventuras en Asturias</agencia>
		<descripcion>Es una forma muy atractiva de contemplar y disfrutar de los maravillosos paisajes del oriente asturiano</descripcion>
		<personas>Apto para cualquiera</personas>
		<lugar>Soto de Cangas</lugar>
        <direccion>Avenida Covadonga, Cangas de Onis</direccion>
		<coordenadas latitud = "43.3448397" longitud = "-5.0834717" altitud = "237"></coordenadas>
		<bibliografias>
			<bibliografia link = "https://www.aventurasenasturias.com/aventuras_en_asturias_actividades.php?aventurasID = 149"></bibliografia>
			<bibliografia link = "https://en.wikipedia.org/wiki/Cangas_de_On%C3%ADs"></bibliografia>
			<bibliografia link = "https://www.escapadarural.com/que-hacer/soto-de-cangas"></bibliografia>
		</bibliografias>
        <recomendacion>8</recomendacion>
		<hitos>
			<hito>
                <nombre>Cangas de Onis</nombre>
				<descripcion>Llegada a Cangas de Onis</descripcion>
				<coordenadas latitud = "43.3145292" longitud = "-5.0656317" altitud = "424"></coordenadas>
				<distancia km = "4" ></distancia>
				<fotos>
					<foto link = "https://www.cangasaventura.com/wp-content/uploads/2019/06/Imagen-reducida-para-web.jpg"></foto>
				</fotos>
			</hito>
			<hito>
                <nombre>Arriondas</nombre>
				<descripcion>Llegada a Arriondas</descripcion>
				<coordenadas latitud = "43.3892173" longitud = "-5.1848708" altitud = "118"></coordenadas>
				<distancia km = "7" ></distancia>
				<fotos>
					<foto link = "https://i.pinimg.com/originals/fb/20/9e/fb209e840fb6ca1ea83069a45397d696.jpg"></foto>
				</fotos>
			</hito>
			<hito>
                <nombre>Ribadesella</nombre>
				<descripcion>Llegada a Ribadesella (el tramo mas largo)</descripcion>
				<coordenadas latitud = "43.4617129" longitud = "-5.0587479" altitud = "0"></coordenadas>
				<distancia km = "15" ></distancia>
				<fotos>
					<foto link = "https://www.ecestaticos.com/image/clipping/a8d9be9f80869c615b6d989c04791f22/opening.jpg"></foto>
				</fotos>
                <videos>
                    <video link = "https://www.youtube.com/watch?v=fWgjmn_64V4"></video> 
                </videos>
			</hito>
		</hitos>
    </ruta>
    <ruta titulo = "Caballos en Potes">
        <tipo>Turistica</tipo>
		<dificultad>9</dificultad>
        <duracion>5 horas</duracion>
        <inicio>13/05/2021</inicio>
		<agencia>Aventuras en Asturias</agencia>
		<descripcion>Los caballos nos harán sentirnos integrados en la naturaleza, ya que es un medio de transporte silencioso y poco agresivo. Lo unico es la duracion, la cual es larga</descripcion>
		<personas>Perfecto para adultos, o menores experimentados</personas>
		<lugar>Potes</lugar>
        <direccion>Avenida Covadonga, Cangas de Onis</direccion>
		<coordenadas latitud = "43.1536831" longitud = "-4.623428" altitud = "522"></coordenadas>
		<bibliografias>
			<bibliografia link = "https://www.aventurasenasturias.com/aventuras_en_asturias_actividades.php?aventurasID = 251"></bibliografia>
			<bibliografia link = "https://en.wikipedia.org/wiki/Cangas_de_On%C3%ADs"></bibliografia>
			<bibliografia link = "https://en.wikipedia.org/wiki/Ribadesella"></bibliografia>
		</bibliografias>
        <recomendacion>6</recomendacion>
		<hitos>
			<hito>
                <nombre>Cangas de Onis</nombre>
				<descripcion>Llegada a Cangas de Onis (el tramo mas largo)</descripcion>
				<coordenadas latitud = "43.3145292" longitud = "-5.0656317" altitud = "424"></coordenadas>
				<distancia km = "80" ></distancia>
				<fotos>
					<foto link = "https://www.cangasaventura.com/wp-content/uploads/2019/06/Imagen-reducida-para-web.jpg"></foto>
				</fotos>
			</hito>
			<hito>
                <nombre>Arriondas</nombre>
				<descripcion>Llegada a Arriondas</descripcion>
				<coordenadas latitud = "43.3892173" longitud = "-5.1848708" altitud = "118"></coordenadas>
				<distancia km = "22" ></distancia>
				<tiempo>57 minutos</tiempo>
				<fotos>
					<foto link = "https://i.pinimg.com/originals/fb/20/9e/fb209e840fb6ca1ea83069a45397d696.jpg"></foto>
				</fotos> 
			</hito>
			<hito>
                <nombre>Ribadesella</nombre>
				<descripcion>Llegada a Ribadesella</descripcion>
				<coordenadas latitud = "43.4617129" longitud = "-5.0587479" altitud = "0"></coordenadas>
				<distancia km = "19" ></distancia>
				<fotos>
					<foto link = "https://www.ecestaticos.com/image/clipping/a8d9be9f80869c615b6d989c04791f22/opening.jpg"></foto>
				</fotos>
			</hito>
		</hitos>
    </ruta>
    <ruta titulo = "Caballos en Unquera">
        <tipo>Turistica</tipo>
		<dificultad>6</dificultad>
        <duracion>1, 1 y media o incluso 2 horas</duracion>
		<agencia>Aventuras en Asturias</agencia>
		<descripcion>Las rutas a caballo por Unquera se realizan por el entorno de la “Sierra de Prio”, con muy buenas vistas hacía el mar Cantábrico y los Picos de Europa.</descripcion>
		<personas>Apta para todos los publicos</personas>
		<lugar>Unquera</lugar>
        <direccion>Avenida Covadonga, Cangas de Onis</direccion>
		<coordenadas latitud = "43.3733637" longitud = "-4.5184513" altitud = "91"></coordenadas>
		<bibliografias>
			<bibliografia link = "https://en.wikipedia.org/wiki/Unquera"></bibliografia>
			<bibliografia link = "https://en.wikipedia.org/wiki/Cangas_de_On%C3%ADs"></bibliografia>
			<bibliografia link = "https://en.wikipedia.org/wiki/Ribadesella"></bibliografia>
		</bibliografias>
        <recomendacion>9</recomendacion>
		<hitos>
			<hito>
                <nombre>Cangas de Onis</nombre>
				<descripcion>Llegada a Cangas de Onis (el tramo mas largo)</descripcion>
				<coordenadas latitud = "43.3145292" longitud = "-5.0656317" altitud = "424"></coordenadas>
				<distancia km = "66" ></distancia>
				<fotos>
					<foto link = "https://www.cangasaventura.com/wp-content/uploads/2019/06/Imagen-reducida-para-web.jpg"></foto>
				</fotos>
			</hito>
			<hito>
                <nombre>Arriondas</nombre>
				<descripcion>Llegada a Arriondas</descripcion>
				<coordenadas latitud = "43.3892173" longitud = "-5.1848708" altitud = "118"></coordenadas>
				<distancia km = "22" ></distancia>
				<fotos>
					<foto link = "https://i.pinimg.com/originals/fb/20/9e/fb209e840fb6ca1ea83069a45397d696.jpg"></foto>
				</fotos>
			</hito>
			<hito>
                <nombre>Ribadesella</nombre>
				<descripcion>Llegada a Ribadesella</descripcion>
				<coordenadas latitud = "43.4617129" longitud = "-5.0587479" altitud = "0"></coordenadas>
				<distancia km = "19" ></distancia>
				<fotos>
					<foto link = "https://www.ecestaticos.com/image/clipping/a8d9be9f80869c615b6d989c04791f22/opening.jpg"></foto>
				</fotos>
			</hito>
		</hitos>
    </ruta>
</rutasCaballo>
